version: '3.8'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: client.dockerfile
    networks:
      - backend
    depends_on:
      - server
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/packages/client/node_modules
    restart: unless-stopped
    ports:
      - 3000:3000
  server:
    container_name: server
    build:
      context: .
      dockerfile: server.dockerfile
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/packages/server/node_modules
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 8000:8000

networks:
  backend:
    driver: bridge